apiVersion: apps/v1
kind:  DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    tier: frontend
spec:
  template:
    metadata:
      labels:
        tier: frontend
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      tier: frontend
